-- MySQL Script generated by MySQL Workbench
-- Mon May 24 21:45:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema med
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema med
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `med` DEFAULT CHARACTER SET utf8 ;
USE `med` ;

-- -----------------------------------------------------
-- Table `med`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `med`.`category` (
  `idC` INT NOT NULL AUTO_INCREMENT,
  `OBSL` VARCHAR(255) NOT NULL,
  `Price` INT NOT NULL,
  PRIMARY KEY (`idC`),
  UNIQUE INDEX `OBSL` (`OBSL` ASC) VISIBLE,
  UNIQUE INDEX `Price` (`Price` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `med`.`zapis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `med`.`zapis` (
  `idZ` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  `DateTime` DATETIME NULL DEFAULT NULL,
  `Tel` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idZ`),
  UNIQUE INDEX `Name` (`Name` ASC) VISIBLE,
  UNIQUE INDEX `DateTime` (`DateTime` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `med`.`spisok`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `med`.`spisok` (
  `idS` INT NOT NULL AUTO_INCREMENT,
  `OBSL` VARCHAR(255) NULL DEFAULT NULL,
  `BDate` YEAR NULL DEFAULT NULL,
  `DName` VARCHAR(45) NULL DEFAULT NULL,
  `Price` INT NULL DEFAULT NULL,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  `DateTime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idS`),
  INDEX `OBSL_idx` (`OBSL` ASC) VISIBLE,
  INDEX `Price_idx` (`Price` ASC) VISIBLE,
  INDEX `Name_idx` (`Name` ASC) INVISIBLE,
  INDEX `DateTime_idx` (`DateTime` ASC) VISIBLE,
  CONSTRAINT `OBSL`
    FOREIGN KEY (`OBSL`)
    REFERENCES `med`.`category` (`OBSL`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Price`
    FOREIGN KEY (`Price`)
    REFERENCES `med`.`category` (`Price`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Name`
    FOREIGN KEY (`Name`)
    REFERENCES `med`.`zapis` (`Name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `DateTime`
    FOREIGN KEY (`DateTime`)
    REFERENCES `med`.`zapis` (`DateTime`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
